language: php
php:
  - 7.0
  - 7.1
directories:
  - $HOME/.composer/cache/files
install: composer global require "squizlabs/php_codesniffer=*" --no-interaction --prefer-dist
script:
  - composer install --no-interaction --prefer-dist
  - $HOME/.composer/vendor/bin/phpcs .  --runtime-set ignore_warnings_on_exit 1
